import 'package:decent_bench/features/workspace/application/menu_command_registry.dart';
import 'package:decent_bench/features/workspace/infrastructure/shortcut_config_service.dart';
import 'package:flutter/material.dart';

const List<String> kMenuTopLevelOrder = <String>[
  'File',
  'Edit',
  'Import',
  'Export',
  'View',
  'Tools',
  'Help',
];

enum MenuContractBehavior { implemented, deferred }

class MenuContractEntry {
  const MenuContractEntry({
    required this.commandId,
    required this.label,
    required this.topLevelMenu,
    required this.behavior,
    required this.enabledWithOpenDatabase,
    required this.enabledWithoutOpenDatabase,
    this.icon = Icons.circle_outlined,
  });

  final String commandId;
  final String label;
  final String topLevelMenu;
  final MenuContractBehavior behavior;
  final bool enabledWithOpenDatabase;
  final bool enabledWithoutOpenDatabase;
  final IconData icon;

  bool enabledForDatabaseState({required bool hasOpenDatabase}) {
    return hasOpenDatabase
        ? enabledWithOpenDatabase
        : enabledWithoutOpenDatabase;
  }

  bool get isDeferred => behavior == MenuContractBehavior.deferred;
}

const List<MenuContractEntry> kMenuCommandContract = <MenuContractEntry>[
  MenuContractEntry(
    commandId: 'file_new',
    label: 'New',
    topLevelMenu: 'File',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.note_add_outlined,
  ),
  MenuContractEntry(
    commandId: 'file_open',
    label: 'Open...',
    topLevelMenu: 'File',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.folder_open_outlined,
  ),
  MenuContractEntry(
    commandId: 'file_open_project',
    label: 'Open Project...',
    topLevelMenu: 'File',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.folder_special_outlined,
  ),
  MenuContractEntry(
    commandId: 'file_save',
    label: 'Save',
    topLevelMenu: 'File',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.save_outlined,
  ),
  MenuContractEntry(
    commandId: 'file_save_as',
    label: 'Save As...',
    topLevelMenu: 'File',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.save_as_outlined,
  ),
  MenuContractEntry(
    commandId: 'file_export_project',
    label: 'Export Project...',
    topLevelMenu: 'File',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.drive_folder_upload_outlined,
  ),
  MenuContractEntry(
    commandId: 'file_close',
    label: 'Close',
    topLevelMenu: 'File',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.close_outlined,
  ),
  MenuContractEntry(
    commandId: 'file_exit',
    label: 'Exit',
    topLevelMenu: 'File',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.power_settings_new_outlined,
  ),
  MenuContractEntry(
    commandId: 'edit_undo',
    label: 'Undo',
    topLevelMenu: 'Edit',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.undo_outlined,
  ),
  MenuContractEntry(
    commandId: 'edit_redo',
    label: 'Redo',
    topLevelMenu: 'Edit',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.redo_outlined,
  ),
  MenuContractEntry(
    commandId: 'edit_cut',
    label: 'Cut',
    topLevelMenu: 'Edit',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.content_cut_outlined,
  ),
  MenuContractEntry(
    commandId: 'edit_copy',
    label: 'Copy',
    topLevelMenu: 'Edit',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.copy_outlined,
  ),
  MenuContractEntry(
    commandId: 'edit_paste',
    label: 'Paste',
    topLevelMenu: 'Edit',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.content_paste_outlined,
  ),
  MenuContractEntry(
    commandId: 'edit_find',
    label: 'Find',
    topLevelMenu: 'Edit',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.search_outlined,
  ),
  MenuContractEntry(
    commandId: 'edit_find_next',
    label: 'Find Next',
    topLevelMenu: 'Edit',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.find_replace_outlined,
  ),
  MenuContractEntry(
    commandId: 'edit_select_all',
    label: 'Select All',
    topLevelMenu: 'Edit',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.select_all_outlined,
  ),
  MenuContractEntry(
    commandId: 'import_excel',
    label: 'Import Excel...',
    topLevelMenu: 'Import',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.table_chart_outlined,
  ),
  MenuContractEntry(
    commandId: 'import_sqlite',
    label: 'Import SQLite...',
    topLevelMenu: 'Import',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.storage_outlined,
  ),
  MenuContractEntry(
    commandId: 'import_sql_dump',
    label: 'Import SQL Dump...',
    topLevelMenu: 'Import',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.description_outlined,
  ),
  MenuContractEntry(
    commandId: 'import_from_database',
    label: 'Import From Database...',
    topLevelMenu: 'Import',
    behavior: MenuContractBehavior.deferred,
    enabledWithOpenDatabase: false,
    enabledWithoutOpenDatabase: false,
    icon: Icons.cloud_sync_outlined,
  ),
  MenuContractEntry(
    commandId: 'import_rerun_last',
    label: 'Re-run Last Import',
    topLevelMenu: 'Import',
    behavior: MenuContractBehavior.deferred,
    enabledWithOpenDatabase: false,
    enabledWithoutOpenDatabase: false,
    icon: Icons.restart_alt_outlined,
  ),
  MenuContractEntry(
    commandId: 'import_open_wizard',
    label: 'Open Import Wizard...',
    topLevelMenu: 'Import',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.file_open_outlined,
  ),
  MenuContractEntry(
    commandId: 'export_results_csv',
    label: 'Export Results as CSV...',
    topLevelMenu: 'Export',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.file_download_outlined,
  ),
  MenuContractEntry(
    commandId: 'export_results_json',
    label: 'Export Results as JSON...',
    topLevelMenu: 'Export',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.data_object_outlined,
  ),
  MenuContractEntry(
    commandId: 'export_results_parquet',
    label: 'Export Results as Parquet...',
    topLevelMenu: 'Export',
    behavior: MenuContractBehavior.deferred,
    enabledWithOpenDatabase: false,
    enabledWithoutOpenDatabase: false,
    icon: Icons.view_column_outlined,
  ),
  MenuContractEntry(
    commandId: 'export_results_excel',
    label: 'Export Results as Excel...',
    topLevelMenu: 'Export',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.table_view_outlined,
  ),
  MenuContractEntry(
    commandId: 'export_table',
    label: 'Export Table...',
    topLevelMenu: 'Export',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.table_rows_outlined,
  ),
  MenuContractEntry(
    commandId: 'export_schema',
    label: 'Export Schema...',
    topLevelMenu: 'Export',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.schema_outlined,
  ),
  MenuContractEntry(
    commandId: 'export_rerun_last',
    label: 'Re-run Last Export',
    topLevelMenu: 'Export',
    behavior: MenuContractBehavior.deferred,
    enabledWithOpenDatabase: false,
    enabledWithoutOpenDatabase: false,
    icon: Icons.replay_outlined,
  ),
  MenuContractEntry(
    commandId: 'view_reset_layout',
    label: 'Reset Layout',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.space_dashboard_outlined,
  ),
  MenuContractEntry(
    commandId: 'view_toggle_schema',
    label: 'Show/Hide Schema Explorer',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.account_tree_outlined,
  ),
  MenuContractEntry(
    commandId: 'view_toggle_properties',
    label: 'Show/Hide Properties',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.info_outline,
  ),
  MenuContractEntry(
    commandId: 'view_toggle_results',
    label: 'Show/Hide Results',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.table_view_outlined,
  ),
  MenuContractEntry(
    commandId: 'view_toggle_status_bar',
    label: 'Show/Hide Status Bar',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.horizontal_rule_outlined,
  ),
  MenuContractEntry(
    commandId: 'view_command_palette',
    label: 'Command Palette...',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.search_outlined,
  ),
  MenuContractEntry(
    commandId: 'view_zoom_in',
    label: 'Zoom In',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.zoom_in_outlined,
  ),
  MenuContractEntry(
    commandId: 'view_zoom_out',
    label: 'Zoom Out',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.zoom_out_outlined,
  ),
  MenuContractEntry(
    commandId: 'view_zoom_reset',
    label: 'Reset Zoom',
    topLevelMenu: 'View',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.center_focus_strong_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_run_query',
    label: 'Run Query',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.play_arrow_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_run_buffer',
    label: 'Run Buffer',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.subject_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_stop_query',
    label: 'Stop Query',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: false,
    enabledWithoutOpenDatabase: false,
    icon: Icons.stop_circle_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_format_sql',
    label: 'Format SQL',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.auto_fix_high_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_new_query_tab',
    label: 'New Query Tab',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.add_box_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_entity_relationship_diagram',
    label: 'Entity Relationship Diagram',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.account_tree_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_export_erd_image',
    label: 'Export ERD Image...',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.image_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_saved_queries',
    label: 'Saved Queries',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.bookmarks_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_branch_workbench',
    label: 'Branch & Snapshots',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.account_tree_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_create_snapshot',
    label: 'Create Snapshot...',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.camera_alt_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_create_branch',
    label: 'Create Branch...',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.call_split_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_branch_diff',
    label: 'Branch Diff...',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.compare_arrows_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_restore_branch',
    label: 'Restore Branch...',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.restore_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_merge_branch',
    label: 'Merge Branch...',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.merge_type,
  ),
  MenuContractEntry(
    commandId: 'tools_view_log',
    label: 'View Log',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.receipt_long_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_query_history',
    label: 'Query History',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.history_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_database_statistics',
    label: 'Database Statistics',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.monitor_heart_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_open_web_console',
    label: 'Open Web Console',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: false,
    icon: Icons.open_in_browser_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_snippets',
    label: 'Manage Snippets',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.library_books_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_manage_connections',
    label: 'Manage Connections',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.deferred,
    enabledWithOpenDatabase: false,
    enabledWithoutOpenDatabase: false,
    icon: Icons.settings_ethernet_outlined,
  ),
  MenuContractEntry(
    commandId: 'tools_options',
    label: 'Options / Preferences',
    topLevelMenu: 'Tools',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.tune_outlined,
  ),
  MenuContractEntry(
    commandId: 'help_docs',
    label: 'Documentation',
    topLevelMenu: 'Help',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.menu_book_outlined,
  ),
  MenuContractEntry(
    commandId: 'help_keyboard_shortcuts',
    label: 'Keyboard Shortcuts',
    topLevelMenu: 'Help',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.keyboard_outlined,
  ),
  MenuContractEntry(
    commandId: 'help_about',
    label: 'About Decent Bench',
    topLevelMenu: 'Help',
    behavior: MenuContractBehavior.implemented,
    enabledWithOpenDatabase: true,
    enabledWithoutOpenDatabase: true,
    icon: Icons.info_outline,
  ),
];

Iterable<MenuContractEntry> commandEntriesForTopLevel(String topLevelMenu) {
  return kMenuCommandContract.where(
    (MenuContractEntry entry) => entry.topLevelMenu == topLevelMenu,
  );
}

MenuCommandRegistry buildAuditedMenuCommandRegistry({
  required bool hasOpenDatabase,
  required List<String> invokeLog,
  Map<String, ShortcutBinding> shortcuts = const <String, ShortcutBinding>{},
}) {
  return MenuCommandRegistry(
    commands: <MenuCommand>[
      for (final entry in kMenuCommandContract)
        MenuCommand(
          id: entry.commandId,
          label: entry.label,
          icon: entry.icon,
          enabled: entry.enabledForDatabaseState(
            hasOpenDatabase: hasOpenDatabase,
          ),
          shortcut: shortcuts[entry.commandId],
          onInvoke: () async {
            invokeLog.add(entry.commandId);
          },
        ),
    ],
  );
}
