import 'saved_query_models.dart';
import 'workspace_models.dart';

enum SdkLanguage { typescript }

class SdkGenerationIr {
  const SdkGenerationIr({
    required this.schemaFingerprint,
    required this.engineVersion,
    required this.tables,
    required this.savedQueries,
    required this.warnings,
  });

  final String schemaFingerprint;
  final String engineVersion;
  final List<SdkTableIr> tables;
  final List<SdkSavedQueryIr> savedQueries;
  final List<String> warnings;

  SdkTableIr? tableNamed(String name) {
    for (final table in tables) {
      if (table.name == name) {
        return table;
      }
    }
    return null;
  }

  SdkSavedQueryIr? savedQueryById(String id) {
    for (final query in savedQueries) {
      if (query.id == id) {
        return query;
      }
    }
    return null;
  }
}

class SdkTableIr {
  const SdkTableIr({
    required this.name,
    required this.dartName,
    required this.typescriptName,
    required this.temporary,
    required this.columns,
  });

  final String name;
  final String dartName;
  final String typescriptName;
  final bool temporary;
  final List<SdkFieldIr> columns;
}

class SdkSavedQueryIr {
  const SdkSavedQueryIr({
    required this.id,
    required this.name,
    required this.typescriptName,
    required this.sql,
    required this.schemaFingerprint,
    required this.parameters,
    required this.resultColumns,
    required this.warnings,
  });

  final String id;
  final String name;
  final String typescriptName;
  final String sql;
  final String schemaFingerprint;
  final List<SdkFieldIr> parameters;
  final List<SdkFieldIr> resultColumns;
  final List<String> warnings;
}

class SdkFieldIr {
  const SdkFieldIr({
    required this.name,
    required this.typescriptName,
    required this.sourceType,
    required this.typescriptType,
    required this.nullable,
    required this.nativeType,
    required this.generated,
    required this.primaryKey,
    required this.enumLabels,
  });

  final String name;
  final String typescriptName;
  final String sourceType;
  final String typescriptType;
  final bool nullable;
  final NativeTypeDescriptor nativeType;
  final bool generated;
  final bool primaryKey;
  final List<String> enumLabels;
}

class SdkCompatibilityReport {
  const SdkCompatibilityReport({
    required this.schemaDrifted,
    required this.breakingChanges,
    required this.warnings,
  });

  final bool schemaDrifted;
  final List<String> breakingChanges;
  final List<String> warnings;

  bool get isBreaking => breakingChanges.isNotEmpty;
}

SdkGenerationIr buildSdkGenerationIr({
  required SchemaSnapshot schema,
  ToolingMetadata? toolingMetadata,
  SavedQueryLibrary savedQueryLibrary = SavedQueryLibrary.empty,
}) {
  final warnings = <String>[];
  final tables = <SdkTableIr>[
    for (final table in schema.tables)
      SdkTableIr(
        name: table.name,
        dartName: _pascalIdentifier(table.name),
        typescriptName: _pascalIdentifier(table.name),
        temporary: table.temporary,
        columns: <SdkFieldIr>[
          for (final column in table.columns)
            _fieldFromSchemaColumn(
              tableName: table.name,
              column: column,
              toolingMetadata: toolingMetadata,
            ),
        ],
      ),
  ];
  final queries = <SdkSavedQueryIr>[
    for (final query in savedQueryLibrary.queries)
      _savedQueryIr(query, toolingMetadata),
  ]..sort((left, right) => left.typescriptName.compareTo(right.typescriptName));
  return SdkGenerationIr(
    schemaFingerprint: toolingMetadata?.schemaFingerprint ?? '',
    engineVersion: toolingMetadata?.engineVersion ?? '',
    tables: tables,
    savedQueries: queries,
    warnings: warnings,
  );
}

String generateTypeScriptSdk(SdkGenerationIr ir) {
  final buffer = StringBuffer()
    ..writeln('// Generated by Decent Bench. Do not edit by hand.')
    ..writeln(
      "export const schemaFingerprint = '${_escapeSingle(ir.schemaFingerprint)}';",
    );
  if (ir.engineVersion.trim().isNotEmpty) {
    buffer.writeln(
      "export const engineVersion = '${_escapeSingle(ir.engineVersion)}';",
    );
  }
  buffer
    ..writeln()
    ..writeln(
      'export type DecentSpatialValue = string | { type: string; coordinates: unknown };',
    );

  for (final table in ir.tables) {
    buffer
      ..writeln()
      ..writeln('export interface ${table.typescriptName}Row {');
    for (final column in table.columns) {
      buffer.writeln(_typescriptProperty(column));
    }
    buffer.writeln('}');
  }

  for (final query in ir.savedQueries) {
    buffer
      ..writeln()
      ..writeln('export interface ${query.typescriptName}Params {');
    if (query.parameters.isEmpty) {
      buffer.writeln('  // This query declares no parameters.');
    } else {
      for (final parameter in query.parameters) {
        buffer.writeln(_typescriptProperty(parameter));
      }
    }
    buffer
      ..writeln('}')
      ..writeln()
      ..writeln('export interface ${query.typescriptName}Row {');
    if (query.resultColumns.isEmpty) {
      buffer.writeln('  // Result metadata is unavailable.');
    } else {
      for (final column in query.resultColumns) {
        buffer.writeln(_typescriptProperty(column));
      }
    }
    buffer.writeln('}');
  }

  if (ir.warnings.isNotEmpty ||
      ir.savedQueries.any((query) => query.warnings.isNotEmpty)) {
    buffer
      ..writeln()
      ..writeln('export const generationWarnings = [');
    for (final warning in ir.warnings) {
      buffer.writeln("  '${_escapeSingle(warning)}',");
    }
    for (final query in ir.savedQueries) {
      for (final warning in query.warnings) {
        buffer.writeln("  '${_escapeSingle('${query.name}: $warning')}',");
      }
    }
    buffer.writeln('] as const;');
  }

  return buffer.toString();
}

SdkCompatibilityReport compareSdkGenerationIr({
  required SdkGenerationIr previous,
  required SdkGenerationIr current,
}) {
  final breaking = <String>[];
  final warnings = <String>[];
  if (previous.schemaFingerprint != current.schemaFingerprint) {
    warnings.add('Schema fingerprint changed.');
  }

  for (final oldTable in previous.tables) {
    final newTable = current.tableNamed(oldTable.name);
    if (newTable == null) {
      breaking.add('Table removed: ${oldTable.name}.');
      continue;
    }
    for (final oldColumn in oldTable.columns) {
      final newColumn = newTable.columns.where(
        (column) => column.name == oldColumn.name,
      );
      if (newColumn.isEmpty) {
        breaking.add('Column removed: ${oldTable.name}.${oldColumn.name}.');
        continue;
      }
      final currentColumn = newColumn.first;
      if (oldColumn.typescriptType != currentColumn.typescriptType) {
        breaking.add(
          'Column type changed: ${oldTable.name}.${oldColumn.name} '
          '${oldColumn.typescriptType} -> ${currentColumn.typescriptType}.',
        );
      }
      if (oldColumn.nullable && !currentColumn.nullable) {
        breaking.add(
          'Column nullability narrowed: ${oldTable.name}.${oldColumn.name}.',
        );
      }
    }
  }

  for (final oldQuery in previous.savedQueries) {
    final newQuery = current.savedQueryById(oldQuery.id);
    if (newQuery == null) {
      breaking.add('Saved query removed: ${oldQuery.name}.');
      continue;
    }
    if (oldQuery.schemaFingerprint != newQuery.schemaFingerprint) {
      warnings.add('Saved query schema fingerprint changed: ${oldQuery.name}.');
    }
  }

  return SdkCompatibilityReport(
    schemaDrifted: previous.schemaFingerprint != current.schemaFingerprint,
    breakingChanges: breaking,
    warnings: warnings,
  );
}

SdkFieldIr _fieldFromSchemaColumn({
  required String tableName,
  required SchemaColumn column,
  required ToolingMetadata? toolingMetadata,
}) {
  final typeMetadata = toolingMetadata?.columnTypeFor(
    tableName: tableName,
    columnName: column.name,
  );
  final nativeType =
      typeMetadata?.nativeTypeDescriptor ??
      describeNativeType(typeName: column.type);
  return SdkFieldIr(
    name: column.name,
    typescriptName: _camelIdentifier(column.name),
    sourceType: column.type,
    typescriptType: _typescriptTypeFor(nativeType, nullable: !column.notNull),
    nullable: !column.notNull,
    nativeType: nativeType,
    generated: column.isGenerated,
    primaryKey: column.primaryKey,
    enumLabels: nativeType.enumLabels,
  );
}

SdkSavedQueryIr _savedQueryIr(
  SavedQuery query,
  ToolingMetadata? toolingMetadata,
) {
  final contract = query.queryContract;
  final warnings = <String>[
    if (query.hasSchemaDrift(toolingMetadata))
      'Saved query schema fingerprint differs from the active database.',
    if (contract == null) 'Query contract metadata is unavailable.',
    ...?contract?.diagnostics,
  ];
  return SdkSavedQueryIr(
    id: query.id,
    name: query.name,
    typescriptName: _pascalIdentifier(query.name),
    sql: query.sql,
    schemaFingerprint: query.schemaFingerprint ?? '',
    parameters: <SdkFieldIr>[
      for (final parameter
          in contract?.parameters ?? const <QueryParameterContract>[])
        _fieldFromParameter(parameter),
    ],
    resultColumns: <SdkFieldIr>[
      for (final column
          in contract?.resultColumns ?? const <QueryResultColumnContract>[])
        _fieldFromResultColumn(column),
    ],
    warnings: warnings,
  );
}

SdkFieldIr _fieldFromParameter(QueryParameterContract parameter) {
  final nativeType = parameter.nativeTypeDescriptor;
  return SdkFieldIr(
    name: parameter.name.isEmpty
        ? 'param${parameter.position}'
        : parameter.name,
    typescriptName: _camelIdentifier(
      parameter.name.isEmpty ? 'param${parameter.position}' : parameter.name,
    ),
    sourceType: parameter.displayType,
    typescriptType: _typescriptTypeFor(
      nativeType,
      nullable: parameter.nullable ?? true,
    ),
    nullable: parameter.nullable ?? true,
    nativeType: nativeType,
    generated: false,
    primaryKey: false,
    enumLabels: nativeType.enumLabels,
  );
}

SdkFieldIr _fieldFromResultColumn(QueryResultColumnContract column) {
  final nativeType = column.nativeTypeDescriptor;
  return SdkFieldIr(
    name: column.name,
    typescriptName: _camelIdentifier(column.name),
    sourceType: column.displayType,
    typescriptType: _typescriptTypeFor(
      nativeType,
      nullable: column.nullable ?? true,
    ),
    nullable: column.nullable ?? true,
    nativeType: nativeType,
    generated: false,
    primaryKey: false,
    enumLabels: nativeType.enumLabels,
  );
}

String _typescriptProperty(SdkFieldIr field) {
  final optional = field.nullable ? '?' : '';
  final type = field.nullable
      ? '${field.typescriptType} | null'
      : field.typescriptType;
  return '  ${field.typescriptName}$optional: $type;';
}

String _typescriptTypeFor(
  NativeTypeDescriptor descriptor, {
  required bool nullable,
}) {
  final base = switch (descriptor.family) {
    NativeTypeFamily.numeric =>
      descriptor.baseTypeName == 'DECIMAL' ? 'string' : 'number',
    NativeTypeFamily.boolean => 'boolean',
    NativeTypeFamily.text || NativeTypeFamily.uuid => 'string',
    NativeTypeFamily.binary => 'Uint8Array',
    NativeTypeFamily.temporal ||
    NativeTypeFamily.network ||
    NativeTypeFamily.macAddress => 'string',
    NativeTypeFamily.spatial => 'DecentSpatialValue',
    NativeTypeFamily.enumValue =>
      descriptor.enumLabels.isEmpty
          ? 'string'
          : descriptor.enumLabels
                .map((label) => "'${_escapeSingle(label)}'")
                .join(' | '),
    NativeTypeFamily.unknown => 'unknown',
  };
  return nullable && base == 'unknown' ? 'unknown' : base;
}

String _pascalIdentifier(String value) {
  final words = _identifierWords(value);
  if (words.isEmpty) {
    return 'Generated';
  }
  return words.map((word) => word[0].toUpperCase() + word.substring(1)).join();
}

String _camelIdentifier(String value) {
  final pascal = _pascalIdentifier(value);
  return pascal[0].toLowerCase() + pascal.substring(1);
}

List<String> _identifierWords(String value) {
  final matches = RegExp(r'[A-Za-z0-9]+').allMatches(value);
  return <String>[for (final match in matches) match.group(0)!.toLowerCase()];
}

String _escapeSingle(String value) {
  return value.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
}
